baseURL = "https://caiyueting.github.io"
languageCode = "zh-tw"
title = "CaiYueTing blog"
theme = "rocinante"
paginate = 3
summaryLength = 0

[markup]
  [markup.highlight]
    style = "monokailight"
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe= true

[author]
  name = "CaiYueTing"

[params]
  mainSections = ["post", "photos"]
  email = "qazxcv367tasi@gmail.com"
  favicon = "icon/favicon.jpg"
  about = """
Hi. I'm **Yue Ting**. I'm a backend developer and a outdoor holic.
Also, I really like free diving, maybe I will be a free diving instructor in the future.

_We can discuss about the coding, freediving or snowboarding._
"""

  [[params.links]]
    [[params.links.link]]
      name = "About"
      href = "https://en.wikipedia.org/wiki/Don_Quixote"
      new_tab = true
    [[params.links.link]]
      name = "Email"
      href = "/contact"
      smart_email_link = true

  [[params.links]]
    [[params.links.link]]
      name = "Github"
      href = "https://github.com/CaiYueTing"
      new_tab = true
    [[params.links.link]]
      name = "Twitter"
      href = "https://twitter.com/"
      new_tab = true
    [[params.links.link]]
      name = "Instagram"
      href = "https://www.instagram.com/tingtsai221/"
      new_tab = true